### ISSUE TITLE
Should add preference screen, to choose only one icon.

### ISSUE THREAD

**Issue by patarapolw** [fawtytoo/activities-icons#3]
Two icon is too much, I want only one.

Actually, I can edit `~/.local/share/gnome-shell/extensions/activities_icons@fawtytoo/extension.js`. Will make a PR if possible.

**Comment by Hayao0819** [comment]
I agree with this too.
However, the repository administrator does not seem to intend to deal with this.

**Comment by fawtytoo** [comment]
Here's a quote from my description:
"The Activities button becomes 2 icons for selecting either Applications or Workspaces in the overview."

As you can see, it's supposed to have 2 icons. To remove one would break the purpose of its design.

**Comment by Hayao0819** [comment]
Depending on the other extension, you may only use either the workspace or the application.
Being able to make choices gives the user more freedom.

**Comment by fawtytoo** [comment]
Before I'm willing to break from its intended design, I need to know what the purpose is in hiding one of the icons.

The idea of this extension was to give access to both Applications and Workspaces. This already gives more choice than the Gnome 'Activities' button.

**Comment by Hayao0819** [comment]
The Gnome official character activity button isn't cool. Also, because it has a large width, it will be an obstacle when using it on Dash to Panel.
This extension replaces the text with an image, which can reduce the width.

**Comment by fawtytoo** [comment]
Are you saying it doesn't play well with other extensions such as Dash to Panel?

**Comment by Hayao0819** [comment]
I do not know the dash-to-panel 's function . If it exists, I'm sorry.

**Comment by fawtytoo** [comment]
Closing as there is now a fork of this project that has this functionality.
